-- 紧急迁移：添加 student_responses 缺失的列
-- 在 Supabase Dashboard → SQL Editor 中执行
-- 执行日期：2026-07-01

ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q5 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q12 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q19 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q20 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q21 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q22 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q23 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q24 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q25 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q26 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q27 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q28 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q29 TEXT;
ALTER TABLE student_responses ADD COLUMN IF NOT EXISTS q30 TEXT;
